### ISSUE TITLE
Improve output of the echo server

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/jetstack-secure#242]
Currently the output of the echo server is very verbose and hard to read. We'd like to experiment with a more structured output, perhaps with color to help users debug issues using the echo server.

**Comment by j-fuentes** [comment]
Apart from the color, it would be great to process the data gatherers readings, printing the metadata in a nice format, and doing a best effort with the payload (which can be freeform actually).

**Comment by j-fuentes** [comment]
@Weeblin please, consider my comments on #243.
