### ISSUE TITLE
No health endpoint

### ISSUE THREAD

**Issue by hawksight** [jetstack/jetstack-secure#439]
I was checking the chart against some linter type tools and found that the deployment doesn't have any `liveness` or `readiness` probes configured. Having a check in the codebase it seems that we have prometheus metrics but no health endpoint we can use to configure the relevant probes.

For example a tool such as [polaris](https://polaris.docs.fairwinds.com/) indicates that there should be check in place:

```
    readinessProbeMissing                😬 Warning
        Reliability - Readiness probe should be configured
    cpuRequestsMissing                   🎉 Success
        Efficiency - CPU requests are set
    linuxHardening                       🎉 Success
        Security - One of AppArmor, Seccomp, SELinux, or dropping Linux Capabilities are used to restrict containers using unwanted privileges
    livenessProbeMissing                 😬 Warning
        Reliability - Liveness probe should be configured
```

Generally this is best practice to have these configured. So looking for some guidance on the best way to try and implement this is?

The only options I can think right now is:

1. To open up the prometheus metrics (off by default) and use that endpoint as the http endpoint to check for liveness etc
2. Or use the `preflight agent info` command to just return info, for example:

```shell
> kubectl exec -ti jetstack-agent-saas-748f8bb945-ljmmx -- preflight agent info                       
Preflight version:  v0.1.39 linux/amd64
  Commit:  1926f2d424cbea70491bec19e5bfb2cf6c5b1feb
  Built:   Tue, 25 Apr 2023 14:30:11 +0000
  Go:      go1.19 linux/amd64

OAuth2: 
  ClientID:          k3TrDbfLhCgnpAbOiiT2kIE1AbovKzjo
  AuthServerDomain:  auth.jetstack.io
```

Looking for input from the team as to the prefered approach here so I can update the chart.
I've checked the latest (v0.1.20) of `jsctl` for any difference and this also doesn't have any checks in place:

```shell
jsctl clusters connect test_cluster --stdout | yq ea 'select(.kind == "Deployment")
```

**Comment by wallrj** [comment]
I disagree with the introduction of liveness and readiness probes for the sake of silencing such tools.

It is not "best practice" to blindly add liveness and readiness probes. In fact the Kubernetes documentation [cautions against it](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/):
```
Caution:
Liveness probes can be a powerful way to recover from application failures, but they should be used with caution. Liveness probes must be configured carefully to ensure that they truly indicate unrecoverable application failure, for example a deadlock.
```
```
Note:
Incorrect implementation of liveness probes can lead to cascading failures. This results in restarting of container under high load; failed client requests as your application became less scalable; and increased workload on remaining pods due to some failed pods. Understand the difference between readiness and liveness probes and when to apply them for your app.
```
There is no need for a Readiness probe in venafi-kubernetes-agent and probably no need for a liveness probe....especially a dumb ping-pong endpoint....but nevertheless, that is what @maelvls was asked to implement in https://github.com/jetstack/jetstack-secure/pull/580.

So I guess this issue can be closed.
