### ISSUE TITLE
warning: refname 'master' is ambiguous.

### ISSUE THREAD

**Issue by maelvls** [jetstack/jetstack-secure#565]
I kept having:
```
$ git rb -i master       
warning: refname 'master' is ambiguous.
warning: refname 'master' is ambiguous.
```
I noticed that the `master` tag exists along side the `master` branch, which causes all sorts of issues. I'm not sure why the `master` tag was created in the first place, so I'll go ahead and remove it. It pointed to b2384c5:

<img src="https://github.com/user-attachments/assets/3cc5dacc-9438-4bf1-ba6c-98271a8232d6" width="300"> <img src="https://github.com/user-attachments/assets/516b4888-2d0b-4364-a3d6-f74529679273" width="300">

![Screenshot 2024-08-30 at 07 54 34](https://github.com/user-attachments/assets/09de2a26-8d76-433b-9a08-cd9b451f2c0c)

**Comment by wallrj** [comment]
Looks like you removed the tag. Thanks @maelvls 

```console
$ git fetch --all --prune --tags --prune-tags
Fetching origin
From github.com:jetstack/jetstack-secure
 - [deleted]         (none)     -> master
...

$ git tag | grep -i master
```
