### ISSUE TITLE
[Release v1.1.0] Alpha Testing before release

### ISSUE THREAD

**Issue by maelvls** [jetstack/jetstack-secure#586]
Plan:

- [x] ❌ Test 1: OCI Helm Chart Replication
   -> **appVersion is missing the `v` prefix** → not a big deal as the actual `repository` in `values.yaml` is correct, but fixed in https://github.com/jetstack/jetstack-secure/pull/590
- [x] ✅ Test 2: Image Replication
- [x] ✅ Test 3: Install using Helm chart
- [x] ❌ Test 4: Install using venctl
   -> **errors out with "cluster_id is required in Venafi Cloud Key Pair Service Account mode"** → Will be fixed in venctl https://venafi.atlassian.net/browse/VC-36585. 
- [x] ❌ Test 5: Helm: `crds.venafiConnection.include=true` works
   -> **CRD missing**, will be fixed in https://github.com/jetstack/jetstack-secure/pull/587
- [x] ❌ Test 6: Helm: `crds.venafiConnection.include=true` + `crds.forceRemoveValidationAnnotations=true` removes the validation annotations on Kubernetes 1.29
   -> **CRD missing**, will be fixed in https://github.com/jetstack/jetstack-secure/pull/587
- [x] ❌ Test 7: Helm: `crds.venafiConnection.include=true` removes the validation annotations on Kubernetes 1.24
   -> **CRD missing**, will be fixed in https://github.com/jetstack/jetstack-secure/pull/587

## Test 1: OCI Helm Chart Replication

```sh
while read i; do
  r=$(helm show chart $i --version 1.1.0-alpha.0 2>&1)
  if [ $? -eq 0 ]; then
    r=$(echo "$r" | grep -iE '(app|^)version' | tr '\n' ', ')
  fi
  echo "| $i | $r |"
done <<EOF
oci://quay.io/jetstack/charts/venafi-kubernetes-agent
oci://us.gcr.io/jetstack-secure-enterprise/charts/venafi-kubernetes-agent
oci://eu.gcr.io/jetstack-secure-enterprise/charts/venafi-kubernetes-agent
oci://registry.venafi.cloud/charts/venafi-kubernetes-agent
oci://private-registry.venafi.cloud/charts/venafi-kubernetes-agent
oci://private-registry.venafi.eu/charts/venafi-kubernetes-agent
EOF
```

| OCI Helm Chart | Result |
|-------|--------|
| oci://quay.io/jetstack/charts/venafi-kubernetes-agent | appVersion: 1.1.0-alpha.0,version: 1.1.0-alpha.0, |
| oci://us.gcr.io/jetstack-secure-enterprise/charts/venafi-kubernetes-agent | Error: unexpected status from HEAD request to https://us.gcr.io/v2/jetstack-secure-enterprise/charts/venafi-kubernetes-agent/manifests/1.1.0-alpha.0: 401 Unauthorized |
| oci://eu.gcr.io/jetstack-secure-enterprise/charts/venafi-kubernetes-agent | Error: unexpected status from HEAD request to https://eu.gcr.io/v2/jetstack-secure-enterprise/charts/venafi-kubernetes-agent/manifests/1.1.0-alpha.0: 401 Unauthorized |
| oci://registry.venafi.cloud/charts/venafi-kubernetes-agent | appVersion: 1.1.0-alpha.0,version: 1.1.0-alpha.0, |
| oci://private-registry.venafi.cloud/charts/venafi-kubernetes-agent | appVersion: 1.1.0-alpha.0,version: 1.1.0-alpha.0, |
| oci://private-registry.venafi.eu/charts/venafi-kubernetes-agent | appVersion: 1.1.0-alpha.0,version: 1.1.0-alpha.0, |

```sh
while read i; do
  r=$(helm template $i --version 1.1.0-alpha.0 2>&1 | grep image: | cut -d: -f2- | tr -d ' ')
  echo "| $i | $r |"
done <<EOF
oci://quay.io/jetstack/charts/venafi-kubernetes-agent
oci://us.gcr.io/jetstack-secure-enterprise/charts/venafi-kubernetes-agent
oci://eu.gcr.io/jetstack-secure-enterprise/charts/venafi-kubernetes-agent
oci://registry.venafi.cloud/charts/venafi-kubernetes-agent
oci://private-registry.venafi.cloud/charts/venafi-kubernetes-agent
oci://private-registry.venafi.eu/charts/venafi-kubernetes-agent
EOF
```

| OCI Helm Chart | Image |
|-------|--------|
| oci://quay.io/jetstack/charts/venafi-kubernetes-agent | "quay.io/jetstack/venafi-agent:v1.1.0-alpha.0" |
| oci://us.gcr.io/jetstack-secure-enterprise/charts/venafi-kubernetes-agent |  |
| oci://eu.gcr.io/jetstack-secure-enterprise/charts/venafi-kubernetes-agent |  |
| oci://registry.venafi.cloud/charts/venafi-kubernetes-agent | "quay.io/jetstack/venafi-agent:v1.1.0-alpha.0" |
| oci://private-registry.venafi.cloud/charts/venafi-kubernetes-agent | "quay.io/jetstack/venafi-agent:v1.1.0-alpha.0" |
| oci://private-registry.venafi.eu/charts/venafi-kubernetes-agent | "quay.io/jetstack/venafi-agent:v1.1.0-alpha.0" |

## Test 2: Image Replication

| Container Image | Result |
|-------|--------|
| quay.io/jetstack/venafi-agent | OK |
| us.gcr.io/jetstack-secure-enterprise/venafi-agent | Error: fetching manifest us.gcr.io/jetstack-secure-enterprise/venafi-agent:v1.1.0-alpha.0: GET https://us.gcr.io/v2/jetstack-secure-enterprise/venafi-agent/manifests/v1.1.0-alpha.0: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication |
| eu.gcr.io/jetstack-secure-enterprise/venafi-agent | Error: fetching manifest eu.gcr.io/jetstack-secure-enterprise/venafi-agent:v1.1.0-alpha.0: GET https://eu.gcr.io/v2/jetstack-secure-enterprise/venafi-agent/manifests/v1.1.0-alpha.0: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication |
| registry.venafi.cloud/venafi-agent/venafi-agent | OK |
| private-registry.venafi.cloud/venafi-agent/venafi-agent | OK |
| private-registry.venafi.eu/venafi-agent/venafi-agent | OK |

## Test 3: Install using Helm chart

I've used the tenant https://ven-tlspk.venafi.cloud/. To access the API key, use the user `system.admin@tlspk.qa.venafi.io` and the password is visible in the page [Production Accounts](https://venafi.atlassian.net/wiki/spaces/CT/pages/2115404149) (private to Venafi). Then go to the settings and find the API key.

```sh
export APIKEY=...
```

I've then deployed the agent to a Kind cluster (create it first):

```sh
venctl iam service-account agent create --name "$USER temp" \
  --vcp-region US \
  --output json \
  --owning-team $(curl -sS https://api.venafi.cloud/v1/teams -H "tppl-api-key: $APIKEY" | jq '.teams[0].id') \
  --output-file /tmp/agent-credentials.json \
  --api-key $APIKEY
helm upgrade -i -n venafi --create-namespace venafi-kubernetes-agent oci://registry.venafi.cloud/charts/venafi-kubernetes-agent --version 1.1.0-alpha.0 \
  --set config.clusterName="$USER temp" --set config.clientId="$(jq -r .client_id /tmp/agent-credentials.json)"
kubectl create secret generic -n venafi agent-credentials --from-literal=privatekey.pem="$(jq -r .private_key /tmp/agent-credentials.json)" \
  --dry-run=client -o yaml | kubectl apply -f -
```

Result:

```console
$ kubectl logs -n venafi -l app.kubernetes.io/name=venafi-kubernetes-agent --tail=-1 | grep -i -A1 "Posting data to"
2024/10/04 06:24:36 Posting data to: https://api.venafi.cloud/
2024/10/04 06:24:38 Data sent successfully.
```

## Test 4: Install using venctl

```sh
git clone https://gitlab.com/venafi/vaas/applications/tls-protect-for-k8s/venctl
cd venctl
git apply <<EOF
diff --git a/pkg/manifestgen/component_data_gen.go b/pkg/manifestgen/component_data_gen.go
index 9466886..6012b63 100644
--- a/pkg/manifestgen/component_data_gen.go
+++ b/pkg/manifestgen/component_data_gen.go
@@ -32,5 +32,5 @@ var DefaultVersionForChart = map[ComponentName]string{
 	TrustManager:               "v0.12.0",
 	VenafiConnection:           "v0.1.0",
 	VenafiEnhancedIssuer:       "v0.14.0",
-	VenafiKubernetesAgent:      "1.0.0",
+	VenafiKubernetesAgent:      "1.1.0-alpha.0",
 }
EOF
go build .
```

I've used the tenant https://ven-tlspk.venafi.cloud/. To access the API key, use the user `system.admin@tlspk.qa.venafi.io` and the password is visible in the page [Production Accounts](https://venafi.atlassian.net/wiki/spaces/CT/pages/2115404149) (private to Venafi). Then go to the settings and find the API key, and set it in the environment variable:

```sh
export APIKEY=...
```

Then, create a Kind cluster.

Finally, run the following command:

```sh
venctl installation cluster connect --name "$USER 2 temp" --api-key=$APIKEY
```

But I got this:

```log
2024/10/04 06:37:23 Using the Venafi Cloud Key Pair Service Account auth mode since --client-id and --private-key-path were specified.
2024/10/04 06:37:23 ignoring the venafi-cloud.uploader_id field in the config file. This field is not needed in Venafi Cloud Key Pair S
2024/10/04 06:37:23 Using period from config 1m0s
2024/10/04 06:37:23 While evaluating configuration: 1 error occurred:
    * cluster_id is required in Venafi Cloud Key Pair Service Account mode
```

What's weird is that the Cluster ID seems to be optional (the env var doesn't say "required" in the Helm file template), but it should be required.

→ this will be fixed in `venctl`: https://venafi.atlassian.net/browse/VC-36585

### Test 5: Helm: `crds.venafiConnection.include=true` works

The validation fields are present as expected:

```console
$ helm template -n venafi venafi-kubernetes-agent deploy/charts/venafi-kubernetes-agent/ --show-only templates/venafi-connection-crd.yaml --set crds.venafiConnection.include=true | grep validation
                        x-kubernetes-validations:
                        x-kubernetes-validations:
                        x-kubernetes-validations:
                  x-kubernetes-validations:
                        x-kubernetes-validations:
                        x-kubernetes-validations:
                  x-kubernetes-validations:
              x-kubernetes-validations:
```

The CRD is installed correctly on Kubernetes 1.29:

```console
$ kind create cluster --image kindest/node:v1.29.2
$ helm template -n venafi venafi-kubernetes-agent deploy/charts/venafi-kubernetes-agent/ --set crds.venafiConnection.include=true
 | kubectl apply -f-
$ k get crd                                                        
NAME                            CREATED AT
venaficonnections.jetstack.io   2024-10-07T09:30:30Z
```

### Test 6: Helm: `crds.venafiConnection.include=true` + `crds.forceRemoveValidationAnnotations=true` removes the validation annotations on Kubernetes 1.29

On Kubernetes 1.29, CRD is printed and the validation fields aren't outputed:

```console
$ helm template -n venafi venafi-kubernetes-agent deploy/charts/venafi-kubernetes-agent/ --show-only templates/venafi-connection-crd.without-validations.yaml --set crds.venafiConnection.include=true --set crds.forceRemoveValidationAnnotations=true | grep -E 'validation|CustomResource'
# Source: venafi-kubernetes-agent/templates/venafi-connection-crd.without-validations.yaml
kind: CustomResourceDefinition
```

On Kubernetes 1.29, it installs correctly:

```console
$ kind create cluster --image kindest/node:v1.29.2
$ helm template -n venafi venafi-kubernetes-agent deploy/charts/venafi-kubernetes-agent/ --set crds.venafiConnection.include=true --set crds.forceRemoveValidationAnnotations=true
 | kubectl apply -f-
$ k get crd
NAME                            CREATED AT
venaficonnections.jetstack.io   2024-10-07T09:43:43Z
```

### Test 7: Helm: `crds.venafiConnection.include=true` removes the validation annotations on Kubernetes 1.24

It installs correctly on Kubernetes 1.24:

```console
$ kind create cluster --image kindest/node:v1.24.4 --name v1.24.4
$ helm template -n venafi venafi-kubernetes-agent deploy/charts/venafi-kubernetes-agent/ --set crds.venafiConnection.include=true | kubectl apply -f-
customresourcedefinition.apiextensions.k8s.io/venaficonnections.jetstack.io configured
```

[VC-35565]: https://venafi.atlassian.net/browse/VC-35565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by maelvls** [comment]
> appVersion: 1.1.0-alpha.0, version: 1.1.0-alpha.0

Seems like there has been an issue with the `appVersion`. It should say `v1.1.0-alpha.0`, not `1.1.0-alpha.0`.

**Comment by inteon** [comment]
> > appVersion: 1.1.0-alpha.0, version: 1.1.0-alpha.0
> 
> Seems like there has been an issue with the `appVersion`. It should say `v1.1.0-alpha.0`, not `1.1.0-alpha.0`.

We can fix this issue as follows: https://github.com/cert-manager/openshift-routes/blob/main/make/00_mod.mk#L36

**Comment by maelvls** [comment]
Bug summary:

- [x] **appVersion is missing the `v` prefix** → fixed in https://github.com/jetstack/jetstack-secure/pull/590
- [x] -> **errors out with "cluster_id is required in Venafi Cloud Key Pair Service Account mode"** → Deferred to later. Will be fixed in `venctl`: https://venafi.atlassian.net/browse/VC-36585. 
- [x] **CRD missing**, fixed in https://github.com/jetstack/jetstack-secure/pull/587

I can now proceed with v1.1.0!
